name: Cloudflare Pages

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: alphine-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy
        # https://github.com/cloudflare/wrangler-action
        uses: cloudflare/wrangler-action@v3
